### ISSUE TITLE
Small button size in dialog box

### ISSUE THREAD

**Issue by deep-1704** [shlok-007/GoTo#1]
In the dialog box for user trips, buttons are not clearly visible due to the smaller size of the box.
I would recommend:
1. Remove `max-width: 370px` on`dialog` element.
2. Add `width: 390px` on the class `dialog-content`.
<img width="384" alt="Screenshot 2023-08-22 at 7 37 28 PM" src="https://github.com/shlok-007/GoTo/assets/111845726/9033346c-a350-4e3a-b665-e8338cbde7a8">

**Comment by deep-1704** [comment]
Recommended changes will fix the issue.
<img width="415" alt="Screenshot 2023-08-22 at 7 53 15 PM" src="https://github.com/shlok-007/GoTo/assets/111845726/7463217e-5a06-4a01-9599-93fa13e575b7">

**Comment by shlok-007** [comment]
Fixed
